export const ICON_OPTIONS = [
  "cud", "transporte", "cnrt", "beneficios", "turismo", "cultura", "centrosdia", "reclamos",
  "buscar-actividad","buscar-mapa","completar-online","documentos","estacionamiento","evaluacion-medica",
  "exencion-patente","fotocopia","ingresar-sitio","oficina","pase-local","pase-nacional","pase-provincial",
  "peaje","pension","ubicacion","recortar","tarifa-social","turno"
];